runtime: nodejs20
handlers:
  # Serve all static files from the build directory.
  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)